#!/usr/bin/env python3
"""
bpftune dashboard - one-shot installer (schema v2 + Chart.js renderer).

Detects the live bpftune log format, writes the collector and renderer
beside itself, installs the schema sidecar and cron file, migrates
buckets.csv -> buckets.v1.csv once, then runs both scripts and verifies
their output. Idempotent - safe to re-run.

    sudo python3 tools/bpftune-dashboard-install.py
"""
from __future__ import annotations

import glob
import json
import os
import re
import subprocess
import sys
import time

HIST     = "/var/lib/bpftune/history"
LOG_GLOB = "/var/log/bpftune-met-*.log"
CRON     = "/etc/cron.d/bpftune-history"
SCHEMA   = os.path.join(HIST, "buckets.schema.json")
V1       = os.path.join(HIST, "buckets.v1.csv")
V2       = os.path.join(HIST, "buckets.v2.csv")
LEGACY   = os.path.join(HIST, "buckets.csv")

SELF_DIR = os.path.dirname(os.path.abspath(__file__))
COLLECTOR = os.path.join(SELF_DIR, "bpftune-collector.py")
RENDERER  = os.path.join(SELF_DIR, "bpftune-render.py")

CAND_SWAP_SIG   = ("cookie", "from_alg", "to_alg")
CAND_BUCKET_SIG = ("ref_rate", "rate_best_v", "rate_best_i", "instances")
ID_CANDIDATES   = ("bucket", "bucket_id", "bkt", "dst", "dest", "target")

KV = re.compile(r"([A-Za-z_][A-Za-z0-9_]*)=(\S+)")


def _c(code, s):
    return "\033[" + code + "m" + s + "\033[0m"


def say(m):
    print(_c("1;34", "[installer]") + " " + m, flush=True)


def warn(m):
    print(_c("1;33", "[installer]") + " " + m, flush=True)


def die(m):
    print(_c("1;31", "[installer] FATAL:") + " " + m,
          file=sys.stderr, flush=True)
    sys.exit(1)


def write_file(path, text, mode=0o644):
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(text)
    os.chmod(tmp, mode)
    os.replace(tmp, path)


def newest_log():
    logs = sorted(glob.glob(LOG_GLOB), key=os.path.getmtime)
    return logs[-1] if logs else None


def dump_diagnostics(log_path):
    say("first non-empty lines from " + log_path + ":")
    try:
        with open(log_path, errors="replace") as f:
            shown = 0
            for line in f:
                if KV.findall(line):
                    print("    " + line.rstrip()[:240])
                    shown += 1
                    if shown >= 8:
                        break
    except OSError as e:
        print("    (could not read: %s)" % e)
    say("paste the above into chat and I'll match the parser")


def detect_schema(log_path):
    b_shapes, s_shapes = {}, {}
    with open(log_path, errors="replace") as f:
        for i, line in enumerate(f):
            if i >= 5000:
                break
            kv = dict(KV.findall(line))
            if not kv:
                continue
            ks = set(kv)
            if any(s in ks for s in CAND_SWAP_SIG):
                s_shapes.setdefault(frozenset(ks), line.rstrip())
            elif any(s in ks for s in CAND_BUCKET_SIG):
                b_shapes.setdefault(frozenset(ks), line.rstrip())

    if not b_shapes:
        dump_diagnostics(log_path)
        die("could not identify any bucket lines - see the dump above")

    bset, sset = set(), set()
    for sh in b_shapes:
        bset |= sh
    for sh in s_shapes:
        sset |= sh

    b_sig = [s for s in CAND_BUCKET_SIG if s in bset]
    s_sig = [s for s in CAND_SWAP_SIG if s in sset]
    if not s_sig:
        warn("no swap lines detected in sample - swaps.csv stays empty "
             "until a swap occurs (that's fine)")

    b_cols = ["collected_ts", "boot_ts"]
    b_cols += sorted(k for k in bset
                     if k not in ("collected_ts", "boot_ts"))
    for extra in ("srate", "tcp_rmem_min", "tcp_rmem_def", "tcp_rmem_max"):
        if extra not in b_cols:
            b_cols.append(extra)
    b_cols = list(dict.fromkeys(b_cols))

    s_cols = ["collected_ts", "boot_ts"]
    s_cols += sorted(k for k in sset
                     if k not in ("collected_ts", "boot_ts"))
    s_cols = list(dict.fromkeys(s_cols))

    bucket_id = next((c for c in ID_CANDIDATES if c in b_cols), None)

    return {
        "version": 2,
        "detected_from": log_path,
        "detected_at": int(time.time()),
        "bucket_signature": b_sig,
        "swap_signature":   s_sig,
        "bucket_columns":   b_cols,
        "swap_columns":     s_cols,
        "bucket_id_column": bucket_id,
    }


COLLECTOR_SRC = r'''#!/usr/bin/env python3
# AUTO-GENERATED by bpftune-dashboard-install.py - edits here are lost.
"""bpftune history collector - schema v2. Runs every minute from cron.

collected_ts (wall clock) is the ONLY date-safe column. bpftune log
lines carry monotonic BOOT seconds; never derive a date from boot_ts.
"""
import csv, glob, json, os, re, subprocess, sys, time

HIST     = "/var/lib/bpftune/history"
SCHEMA   = os.path.join(HIST, "buckets.schema.json")
BUCKETS  = os.path.join(HIST, "buckets.v2.csv")
SWAPS    = os.path.join(HIST, "swaps.csv")
STATE    = "/var/lib/bpftune/collector.state.json"
LOG_GLOB = "/var/log/bpftune-met-*.log"

KV = re.compile(r"([A-Za-z_][A-Za-z0-9_]*)=(\S+)")


def load_schema():
    with open(SCHEMA) as f:
        return json.load(f)


def read_state():
    try:
        with open(STATE) as f:
            return json.load(f)
    except (OSError, ValueError):
        return {"path": None, "offset": 0}


def write_state(s):
    tmp = STATE + ".tmp"
    with open(tmp, "w") as f:
        json.dump(s, f)
    os.chmod(tmp, 0o600)
    os.replace(tmp, STATE)


def newest_log():
    logs = sorted(glob.glob(LOG_GLOB), key=os.path.getmtime)
    return logs[-1] if logs else None


def tcp_rmem():
    try:
        out = subprocess.run(["sysctl", "-n", "net.ipv4.tcp_rmem"],
                             capture_output=True, text=True,
                             check=True).stdout
        lo, mid, hi = out.split()
        return int(lo), int(mid), int(hi)
    except Exception:
        return "", "", ""


def classify(kv, schema):
    ks = set(kv)
    if any(k in ks for k in schema["swap_signature"]):
        return "swap"
    if any(k in ks for k in schema["bucket_signature"]):
        return "bucket"
    return None


def get_header(path, default):
    if os.path.exists(path) and os.path.getsize(path) > 0:
        with open(path, newline="") as f:
            return next(csv.reader(f), default)
    return default


def append(path, header, rows):
    if not rows:
        return
    created = not (os.path.exists(path) and os.path.getsize(path) > 0)
    with open(path, "a", newline="") as f:
        w = csv.writer(f)
        if created:
            w.writerow(header)
        for r in rows:
            w.writerow([r.get(c, "") for c in header])


def main():
    schema = load_schema()
    log = newest_log()
    if not log:
        print("collector: no log found", file=sys.stderr)
        return 1

    state = read_state()
    offset = state.get("offset", 0) if state.get("path") == log else 0
    ts = int(time.time())
    lo, mid, hi = tcp_rmem()

    b_rows, s_rows = [], []
    with open(log, errors="replace") as f:
        f.seek(offset)
        for line in f:
            kv = dict(KV.findall(line))
            if not kv:
                continue
            kind = classify(kv, schema)
            if kind == "bucket":
                r = dict(kv)
                r["collected_ts"]  = ts
                r["tcp_rmem_min"]  = lo
                r["tcp_rmem_def"]  = mid
                r["tcp_rmem_max"]  = hi
                b_rows.append(r)
            elif kind == "swap":
                r = dict(kv)
                r["collected_ts"] = ts
                s_rows.append(r)
        offset = f.tell()

    append(BUCKETS, get_header(BUCKETS, schema["bucket_columns"]), b_rows)
    append(SWAPS,   get_header(SWAPS,   schema["swap_columns"]),   s_rows)
    write_state({"path": log, "offset": offset})
    print("collector: %d bucket, %d swap, off=%d"
          % (len(b_rows), len(s_rows), offset))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


RENDERER_SRC = r'''#!/usr/bin/env python3
# AUTO-GENERATED by bpftune-dashboard-install.py - edits here are lost.
"""bpftune renderer - static Chart.js dashboard.

Cron: every 5 min. Reads the collector CSVs, writes data/*.json +
index.html into /var/lib/bpftune/history. All downsampling is done
here, server-side, so Chart.js never sees raw rows.

collected_ts is the only date-safe timestamp (boot_ts is monotonic).
"""
import csv, json, math, os, time
from collections import defaultdict

HIST   = "/var/lib/bpftune/history"
DATA   = os.path.join(HIST, "data")
SCHEMA = os.path.join(HIST, "buckets.schema.json")

RANGES = {
    "1h":  (3600,       60),
    "24h": (86400,      300),
    "7d":  (7 * 86400,  3600),
    "all": (None,       21600),
}

EXTRA_COLS = ["ref_rate", "rate_best_i", "rate_best_v", "instances",
              "tcp_rmem_min", "tcp_rmem_def", "tcp_rmem_max", "srate"]


def load_schema():
    try:
        with open(SCHEMA) as f:
            return json.load(f)
    except (OSError, ValueError):
        return {"bucket_id_column": None}


def load_csv(path):
    if not path or not os.path.exists(path):
        return [], []
    with open(path, newline="") as f:
        rd = csv.DictReader(f)
        return rd.fieldnames or [], list(rd)


def to_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def truthy(v):
    return str(v).strip().lower() in ("1", "true", "yes", "y")


def wilson(w, n, z=1.96):
    if n == 0:
        return None, None
    p = w / n
    d = 1 + z * z / n
    c = p + z * z / (2 * n)
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return (c - h) / d, (c + h) / d


def buckets_source():
    for n in ("buckets.v2.csv", "buckets.csv", "buckets.v1.csv"):
        p = os.path.join(HIST, n)
        if os.path.exists(p):
            return p
    return None


def bucket_id(row, col):
    if col and row.get(col):
        return str(row[col])
    return "all"


def bin_series(rows, lo, width, cols):
    acc = defaultdict(list)
    for r in rows:
        t = to_float(r.get("collected_ts"))
        if t is None or (lo is not None and t < lo):
            continue
        acc[int((t - (lo or 0)) // width)].append(r)
    base = lo if lo is not None else 0
    ts, out = [], {c: [] for c in cols}
    for b in sorted(acc):
        ts.append(int(base + b * width + width / 2))
        for c in cols:
            vals = [to_float(r.get(c)) for r in acc[b]]
            vals = [v for v in vals if v is not None]
            out[c].append(sum(vals) / len(vals) if vals else None)
    return ts, out


def write_json(name, obj):
    os.makedirs(DATA, exist_ok=True)
    path = os.path.join(DATA, name)
    tmp  = path + ".tmp"
    with open(tmp, "w") as f:
        json.dump(obj, f, separators=(",", ":"))
    os.replace(tmp, path)


def emit_meta(buckets, algs, bid_col, now):
    rows_24h = [r for r in buckets
                if (to_float(r.get("collected_ts")) or 0) > now - 86400]
    by = defaultdict(list)
    for r in rows_24h:
        by[bucket_id(r, bid_col)].append(r)
    entries = []
    for bid, rs in by.items():
        inst = [to_float(r.get("instances")) for r in rs]
        inst = [v for v in inst if v is not None]
        entries.append({
            "id": bid,
            "points": len(rs),
            "instances_mean": round(sum(inst) / len(inst), 2) if inst else 0,
        })
    entries.sort(key=lambda e: e["instances_mean"], reverse=True)

    header, _ = load_csv(buckets_source())
    write_json("meta.json", {
        "generated_ts":  now,
        "ranges":        list(RANGES),
        "algs":          algs,
        "buckets":       entries,
        "default_bucket": entries[0]["id"] if entries else "all",
        "has_tcp_rmem":  "tcp_rmem_max" in header,
        "has_srate":     "srate" in header,
    })


def emit_bucket(bid, rows, algs, now):
    doc = {"id": bid, "series": {}}
    for rng, (span, width) in RANGES.items():
        lo = None if span is None else now - span
        cols = [f"re_{a}" for a in algs] + EXTRA_COLS
        if rng == "24h":
            cols += [f"mv_{a}" for a in algs]
        ts, out = bin_series(rows, lo, width, cols)
        doc["series"][rng] = {"ts": ts, **out}
    safe = "".join(c if c.isalnum() or c in "-_." else "_" for c in bid)
    write_json(f"bucket_{safe}.json", doc)


def emit_swaps(rows, now):
    doc = {}
    for rng, (span, width) in RANGES.items():
        lo = None if span is None else now - span
        acc = defaultdict(lambda: {0: {"w": 0, "l": 0}, 1: {"w": 0, "l": 0}})
        for r in rows:
            t = to_float(r.get("collected_ts"))
            if t is None or (lo is not None and t < lo):
                continue
            b = int((t - (lo or 0)) // width)
            d = 1 if truthy(r.get("diverges")) else 0
            o = str(r.get("outcome", "")).strip().lower()
            if   o == "win":  acc[b][d]["w"] += 1
            elif o == "loss": acc[b][d]["l"] += 1

        base = lo if lo is not None else 0
        node = {"ts": [], "swaps": []}
        for d in (0, 1):
            node[f"d{d}_rate"] = []
            node[f"d{d}_lo"]   = []
            node[f"d{d}_hi"]   = []
            node[f"d{d}_n"]    = []

        for b in sorted(acc):
            node["ts"].append(int(base + b * width + width / 2))
            total = 0
            for d in (0, 1):
                w, l = acc[b][d]["w"], acc[b][d]["l"]
                n = w + l
                total += n
                lo_, hi_ = wilson(w, n)
                node[f"d{d}_rate"].append(w / n if n else None)
                node[f"d{d}_lo"].append(lo_)
                node[f"d{d}_hi"].append(hi_)
                node[f"d{d}_n"].append(n)
            node["swaps"].append(total)
        doc[rng] = node
    write_json("swaps.json", doc)


def emit_fleet(buckets, bid_col, now):
    lo = now - 86400
    width = 300
    rows = [r for r in buckets
            if (to_float(r.get("collected_ts")) or 0) > lo]
    by = defaultdict(list)
    for r in rows:
        by[bucket_id(r, bid_col)].append(r)

    labels, cov = [], []
    for bid, rs in sorted(by.items()):
        bins = defaultdict(list)
        for r in rs:
            t = to_float(r.get("collected_ts"))
            if t is not None:
                bins[int((t - lo) // width)].append(r)
        if not bins:
            continue
        have = sum(1 for grp in bins.values()
                   if any((to_float(x.get("rate_best_v")) or 0) > 0
                          for x in grp))
        labels.append(bid)
        cov.append(round(100 * have / len(bins), 1))
    write_json("fleet.json", {"buckets": labels, "coverage_24h": cov})


INDEX_HTML = r"""<!doctype html>
<meta charset="utf-8">
<title>bpftune</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
<style>
  :root { color-scheme: light dark; }
  body { font: 13px/1.4 system-ui, sans-serif; margin: 0; padding: 16px; }
  header { display: flex; gap: 12px; align-items: center; flex-wrap: wrap;
           margin-bottom: 16px; }
  h2 { font-size: 14px; margin: 24px 0 6px; }
  select { font: inherit; padding: 2px 6px; }
  .wrap { max-width: 1100px; margin: 0 auto; }
  .muted { color: #888; }
</style>
<div class="wrap">
  <header>
    <h1 style="font-size:16px;margin:0">bpftune</h1>
    <label>bucket <select id="bucket"></select></label>
    <label>range <select id="range"></select></label>
    <span id="gen" class="muted"></span>
  </header>

  <h2>rate_ema per algorithm</h2>
  <canvas id="rate" height="90"></canvas>

  <h2>reference rate</h2>
  <canvas id="ref" height="50"></canvas>

  <h2>tcp_rmem max (bytes)</h2>
  <canvas id="rmem" height="50"></canvas>

  <h2>divergence outcomes - win rate with 95% Wilson CI</h2>
  <canvas id="div" height="70"></canvas>

  <h2>swaps per bin</h2>
  <canvas id="swaps" height="50"></canvas>

  <h2>rate-board coverage, last 24h (% of bins with a leader)</h2>
  <canvas id="fleet" height="70"></canvas>
</div>

<script>
const PALETTE = Array.from({length: 16}, (_, i) =>
  `hsl(${Math.round(i * 360 / 16)},70%,55%)`);

const state  = { meta: null, bucketDoc: null, swaps: null, fleet: null };
const charts = {};

function mk(id, cfg) {
  if (charts[id]) charts[id].destroy();
  charts[id] = new Chart(document.getElementById(id), cfg);
}

async function j(url) {
  const r = await fetch(url, {cache: "no-store"});
  if (!r.ok) throw new Error(`${url}: ${r.status}`);
  return r.json();
}

function lineData(cols, series, ts, colors) {
  return cols.map((c, i) => ({
    label: c,
    data: (series[c] || []).map((y, k) => ({x: ts[k] * 1000, y})),
    borderColor: colors[i % colors.length],
    pointRadius: 0,
    borderWidth: 1.4,
    spanGaps: true,
  }));
}

function timeOpts(extra) {
  const base = {
    responsive: true,
    animation: false,
    interaction: {mode: "nearest", intersect: false},
    scales: {
      x: {type: "time", time: {tooltipFormat: "MM-dd HH:mm"}},
      y: {beginAtZero: false},
    },
    plugins: {legend: {labels: {boxWidth: 8, font: {size: 10}}}},
  };
  return Object.assign(base, extra || {});
}

function renderBucket() {
  const doc = state.bucketDoc, algs = state.meta.algs;
  const rng = document.getElementById("range").value;
  const s = doc.series[rng], ts = s.ts;

  mk("rate", {
    type: "line",
    data: {datasets: lineData(algs.map(a => `re_${a}`), s, ts, PALETTE)},
    options: timeOpts({
      plugins: {legend: {position: "right",
                         labels: {boxWidth: 8, font: {size: 10}}}},
    }),
  });

  mk("ref", {
    type: "line",
    data: {datasets: lineData(["ref_rate"], s, ts, ["#c33"])},
    options: timeOpts(),
  });

  mk("rmem", {
    type: "line",
    data: {datasets: lineData(["tcp_rmem_max"], s, ts, ["#37a"])},
    options: timeOpts({plugins: {legend: {display: false}}}),
  });
}

function renderSwaps() {
  const doc = state.swaps, rng = document.getElementById("range").value;
  const d = doc[rng];
  if (!d) return;
  const ts = d.ts;

  const mkLine = (key, color, dash) => ({
    label: key,
    data: d[key].map((y, k) => ({x: ts[k] * 1000, y})),
    borderColor: color,
    borderDash: dash || [],
    pointRadius: 0,
    borderWidth: 1.5,
    spanGaps: true,
  });

  mk("div", {
    type: "line",
    data: {datasets: [
      mkLine("d1_rate", "#2a7"),
      mkLine("d1_lo",   "#2a7", [4, 3]),
      mkLine("d1_hi",   "#2a7", [4, 3]),
      mkLine("d0_rate", "#a72"),
      mkLine("d0_lo",   "#a72", [4, 3]),
      mkLine("d0_hi",   "#a72", [4, 3]),
    ]},
    options: timeOpts({
      scales: {x: {type: "time"}, y: {min: 0, max: 1}},
    }),
  });

  mk("swaps", {
    type: "bar",
    data: {
      labels: ts.map(t => new Date(t * 1000)),
      datasets: [{label: "swaps", data: d.swaps, backgroundColor: "#69c"}],
    },
    options: Object.assign(timeOpts(), {
      scales: {x: {type: "time"}, y: {beginAtZero: true}},
      plugins: {legend: {display: false}},
    }),
  });
}

function renderFleet() {
  const f = state.fleet;
  mk("fleet", {
    type: "bar",
    data: {
      labels: f.buckets,
      datasets: [{label: "% bins with leader",
                  data: f.coverage_24h, backgroundColor: "#4a8"}],
    },
    options: {
      responsive: true, animation: false, indexAxis: "y",
      scales: {x: {min: 0, max: 100}},
      plugins: {legend: {display: false}},
    },
  });
}

async function loadBucket(id) {
  state.bucketDoc = await j(`data/bucket_${id}.json`);
  renderBucket();
}

async function boot() {
  state.meta  = await j("data/meta.json");
  state.swaps = await j("data/swaps.json");
  state.fleet = await j("data/fleet.json");

  const bs = document.getElementById("bucket");
  bs.innerHTML = state.meta.buckets
    .map(b => `<option value="${b.id}">${b.id} (${b.points})</option>`)
    .join("");
  bs.value = state.meta.default_bucket;

  const rs = document.getElementById("range");
  rs.innerHTML = state.meta.ranges
    .map(r => `<option value="${r}">${r}</option>`).join("");
  rs.value = "24h";

  document.getElementById("gen").textContent =
    "generated " + new Date(state.meta.generated_ts * 1000).toISOString();

  bs.onchange = () => loadBucket(bs.value);
  rs.onchange = () => { renderBucket(); renderSwaps(); };

  await loadBucket(state.meta.default_bucket);
  renderSwaps();
  renderFleet();
}

boot();
"""


def main():
    now = int(time.time())
    bfile = buckets_source()
    header, buckets = load_csv(bfile)
    _, swaps = load_csv(os.path.join(HIST, "swaps.csv"))
    schema = load_schema()
    bid_col = schema.get("bucket_id_column")

    algs = sorted({c[3:] for c in header if c.startswith("re_")})

    by = defaultdict(list)
    for r in buckets:
        by[bucket_id(r, bid_col)].append(r)
    for rs in by.values():
        rs.sort(key=lambda r: to_float(r.get("collected_ts")) or 0)

    emit_meta(buckets, algs, bid_col, now)
    for bid, rs in by.items():
        emit_bucket(bid, rs, algs, now)
    emit_swaps(swaps, now)
    emit_fleet(buckets, bid_col, now)

    with open(os.path.join(HIST, "index.html"), "w") as f:
        f.write(INDEX_HTML)

    print("renderer: %d buckets, %d algs, %d swaps"
          % (len(by), len(algs), len(swaps)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def migrate():
    if os.path.exists(V1) and not os.path.exists(LEGACY):
        say("  v1 already migrated, nothing to do")
        return
    if os.path.exists(LEGACY):
        if os.path.exists(V1):
            warn("  both buckets.csv and buckets.v1.csv exist; leaving both")
        else:
            os.rename(LEGACY, V1)
            say("  renamed buckets.csv -> buckets.v1.csv")
    else:
        say("  no buckets.csv to migrate")


def write_cron():
    body = (
        "# managed by bpftune-dashboard-install.py\n"
        "* * * * * root %s >> /var/log/bpftune-collector.log 2>&1\n"
        "*/5 * * * * root %s >> /var/log/bpftune-collector.log 2>&1\n"
        % (COLLECTOR, RENDERER)
    )
    write_file(CRON, body, 0o644)


def count_data_rows(path):
    if not os.path.exists(path):
        return 0
    with open(path, newline="") as f:
        return max(0, sum(1 for _ in f) - 1)


def run_and_verify():
    before = count_data_rows(V2)
    r = subprocess.run([sys.executable, COLLECTOR],
                       capture_output=True, text=True)
    print("    collector:", r.stdout.strip() or "(no output)")
    if r.returncode != 0:
        print(r.stderr)
        die("collector exited non-zero")

    after = count_data_rows(V2)
    if after == 0:
        die("collector wrote zero rows - schema mismatch? see " + SCHEMA)
    if after <= before:
        warn("collector added no rows (log hasn't grown since last run) "
             "- existing %d rows are fine" % after)

    r = subprocess.run([sys.executable, RENDERER],
                       capture_output=True, text=True)
    print("    renderer:", r.stdout.strip() or "(no output)")
    if r.returncode != 0:
        print(r.stderr)
        die("renderer exited non-zero")

    for p in (os.path.join(HIST, "index.html"),
              os.path.join(HIST, "data", "meta.json")):
        if not os.path.exists(p):
            die("expected output missing: " + p)


def main():
    if os.geteuid() != 0:
        die("must run as root (writes /etc/cron.d and /var/lib/bpftune)")

    os.makedirs(HIST, exist_ok=True)

    log = newest_log()
    if not log:
        die("no bpftune log found at " + LOG_GLOB)
    say("detecting schema from " + log)

    schema = detect_schema(log)
    say("  bucket signature: %s" % schema["bucket_signature"])
    say("  swap signature:   %s" % schema["swap_signature"])
    say("  bucket id column: %s" % schema["bucket_id_column"])
    if schema["bucket_id_column"] is None:
        warn("  no bucket id column recognised - every row will land in "
             "bucket 'all'. Candidates tried: %s" % ", ".join(ID_CANDIDATES))

    say("writing schema sidecar")
    with open(SCHEMA, "w") as f:
        json.dump(schema, f, indent=2)

    say("writing collector and renderer beside installer")
    write_file(COLLECTOR, COLLECTOR_SRC, 0o755)
    write_file(RENDERER,  RENDERER_SRC,  0o755)

    say("compiling")
    for p in (COLLECTOR, RENDERER):
        r = subprocess.run([sys.executable, "-m", "py_compile", p],
                           capture_output=True, text=True)
        if r.returncode != 0:
            print(r.stderr)
            die("py_compile failed on " + p)

    say("migrating v1")
    migrate()

    say("installing cron: " + CRON)
    write_cron()

    say("seeding + verifying")
    run_and_verify()

    print()
    say("done")
    print("    collector: %s" % COLLECTOR)
    print("    renderer:  %s" % RENDERER)
    print("    cron:      %s" % CRON)
    print("    site:      %s/index.html" % HIST)
    print()
    print("  open http://<this-host>:8080/ in a browser")
    print("  tail -f /var/log/bpftune-collector.log")
    print()


if __name__ == "__main__":
    main()
